name:                servant-cli
version:             0.1.0.0
github:              "mstksg/servant-cli"
license:             BSD3
author:              "Justin Le"
maintainer:          "justin@jle.im"
copyright:           "(c) Justin Le 2019"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mstksg/servant-cli#readme>

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wredundant-constraints

dependencies:
- base >= 4.7 && < 5
- text
- optparse-applicative
- servant
- servant-docs
- servant-client
- servant-client-core
- decidable
- singletons
- kan-extensions
- free
- containers
- recursion-schemes
- vinyl
# - servant-server

library:
  source-dirs: src

# executables:
#   servant-cli-exe:
#     main:                Main.hs
#     source-dirs:         app
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - servant-cli

# tests:
#   servant-cli-test:
#     main:                Spec.hs
#     source-dirs:         test
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - servant-cli
