name:                servant-cli
version:             0.1.0.0
github:              "mstksg/servant-cli"
license:             BSD3
author:              "Justin Le"
maintainer:          "justin@jle.im"
copyright:           "(c) Justin Le 2019"

extra-source-files:
- README.md
- CHANGELOG.md

synopsis:            Command line interface for Servant API clients
category:            Web

description: |
  Parse command line arguments into a servant client, from a servant API,
  using /optparse-applicative/ for parsing, displaying help, and
  auto-completion.

  Hooks into the annotation system used by /servant-docs/ to provide descriptions
  for parameters and captures.

  See @example/greet.hs@ for an example usage, and the
  <https://hackage.haskell.org/package/servant-cli README> for a tutorial.

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wredundant-constraints
- -Werror=incomplete-patterns


library:
  source-dirs: src
  dependencies:
  - base >= 4.7 && < 5
  - bytestring
  - case-insensitive
  - containers
  - filepath
  - free
  - http-types
  - kan-extensions
  - optparse-applicative
  - profunctors
  - recursion-schemes
  - servant
  - servant-client-core
  - servant-docs
  - text
  - vinyl

executables:
  greet-cli:
    main:                greet.hs
    source-dirs:         example
    dependencies:
    - aeson
    - base >= 4.7 && < 5
    - bytestring
    - containers
    - http-client
    - optparse-applicative
    - random
    - servant
    - servant-cli
    - servant-client
    - servant-server
    - text
    - vinyl
    - warp
