name:                servant-cli
version:             0.1.0.0
github:              "mstksg/servant-cli"
license:             BSD3
author:              "Justin Le"
maintainer:          "justin@jle.im"
copyright:           "(c) Justin Le 2019"

extra-source-files:
- README.md
- CHANGELOG.md
- example/greet.hs

synopsis:            Command line interface for Servant API clients
category:            Web

description: |
  Parse command line arguments into a servant client, from a servant API.

  Mainly used through 'parseClient' and 'parseHandleClient'. 'parseClient'
  returns a servant client action that returns nested 'Either's for every
  endpoint, but 'parseHandleClient' allows you to conveniently specify how you
  want to combine each endpoint entry into a single result.

  Hooks into the annotation system used by /servant-docs/ to provide descriptions
  for parameters and captures.

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wredundant-constraints
- -Werror=incomplete-patterns

dependencies:
- base >= 4.7 && < 5
- bytestring
- containers
- filepath
- free
- http-types
- case-insensitive
- kan-extensions
- optparse-applicative
- profunctors
- recursion-schemes
- servant
- servant-client-core
- servant-docs
- vinyl
- text

library:
  source-dirs: src
